### PR TITLE
Fix alias tag regression

### LINKED ISSUE #64: add functionality to account for alias parameters

### PR DESCRIPTION
**Pull request by JalexChen**
closes #64

Initially, the new parentTag functionality did not support aliases (which are currently only present on cimg-node). As a result, alias tags like cimg/node:lts or cimg/node:browsers were not being tagged, causing confusion with customers.

This PR implements a fix by adding those tags back in through the docker tag command and is separated out by the different version loop workflows - one for parentTag functionality, and one for cimg's that do not have parentTag functionality

### CODE REVIEW

**Comment by felicianotech** [comment]
Reviewing today.

File: gen-dockerfiles.sh [hunk 1]
```diff
@@ -76,13 +76,27 @@ build_and_push() {
...
+		{ 
+			echo "docker tag $tagless_image:$versionString $tagless_image:$defaultString"
+			echo "docker tag $tagless_image:$versionShortString $tagless_image:$defaultShortString"
+		} >> ./push-images-temp.sh
+	fi
+	
+	if [[ -n $vgAlias1 ]] && [[ "$vgVersion" = "$aliasGroup" ]]; then
+		{
+			echo "docker tag $tagless_image:$versionString $tagless_image:$defaultString"
+			echo "docker tag $tagless_image:$versionShortString $tagless_image:$defaultString"
```
Comment (felicianotech) [inline gen-dockerfiles.sh:97]: This line isn't needed. I'll remove it.
